Book Store/Areas/Writer/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Book_Store.Models;
using PagedList;


namespace Book_Store.Areas.Writer.Controllers
{
    public class WriterController : Controller
    {
        Bookshop_DBEntities db = new Bookshop_DBEntities();
        // GET: Writer/Writer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddWriter()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddWriter(string Name , string Nationality , string BirthDay , string DeathTime , HttpPostedFileBase Fileup, string mytextarea)
        {
            TBL_Writer Writer = new TBL_Writer()
            {
                FullName = Name,
                Nationality = Nationality,
                Birthday = Convert.ToInt32(BirthDay),
                Deathdate = Convert.ToInt32(DeathTime),
                Writer_Content = mytextarea,
                Image = Guid.NewGuid() + Path.GetExtension(Fileup.FileName),
            };
            string MyPath = Server.MapPath("~/Content/img/Writers");
            if (!Directory.Exists(MyPath))
            {
                Directory.CreateDirectory(MyPath);
            }
            string filename = MyPath + "/" + Writer.Image;
            Fileup.SaveAs(MyPath + "/" + Writer.Image);
            string thumbnail = "/thumb_" + Writer.Image;
            WebImage img = new WebImage(MyPath + "/" + Writer.Image);
            img.FileName = thumbnail;
            string thumbnail_path = MyPath + thumbnail;
            img.Resize(100, 100);
            img.Save(thumbnail_path);

            Writer.Image_Thumbnail = thumbnail;

            db.TBL_Writer.Add(Writer);
            db.SaveChanges();
            ViewBag.WritreAdded = "نویسنده با موفقیت ثبت شد";

            return View();
        }


        public ActionResult ShowAllWriters(int page = 1, int pageSize = 2)
        {
            List<TBL_Writer> temp = db.TBL_Writer.OrderByDescending(p => p.ID).ToList();
            PagedList<TBL_Writer> model = new PagedList<TBL_Writer>(temp, page, pageSize);
            return View(model);
        }

        public ActionResult ChangeWriterStatus(int id)
        {
            var temp = db.TBL_Writer.First(p => p.ID == id);
            if(temp.Status == 0)
            {
                temp.Status = 1;
            }
            else
            {
                temp.Status = 0;
            }
            db.SaveChanges();
            return RedirectToAction("ShowAllWriters");
        }

        public ActionResult EditWriter(int id)
        {
            var temp = db.TBL_Writer.First(p => p.ID == id);
            return View(temp);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditWriter(string TID, string Name, string Nationality, string BirthDay, string DeathTime, HttpPostedFileBase Fileup, string mytextarea)
        {
            int WID = Convert.ToInt32(TID);
            var temp = db.TBL_Writer.First(p => p.ID == WID);
            temp.FullName = Name;
            temp.Nationality = Nationality;
            temp.Birthday = Convert.ToInt32(BirthDay);
            temp.Deathdate = Convert.ToInt32(DeathTime);
            temp.Writer_Content = mytextarea;
            db.SaveChanges();
            return RedirectToAction("ShowAllWriters");
        }


        public ActionResult ShowWriterDetail(int id)
        {
            var temp = db.TBL_Writer.First(p => p.ID == id);
            return View(temp);
        }






    }
}

Book Store/Areas/Writer/Views/Writer/AddWriter.cshtml
@{
    ViewBag.Title = "AddWriter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="margin-top:10px;">

    @using (Html.BeginForm("AddWriter", "Writer", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <div class="Frm" id="AddProductForm">
        <h4 style="font-weight:bold;text-align:center;margin-top:50px;color:green;">@ViewBag.WritreAdded</h4><br />

        <h4 style="font-weight:bold;text-align:center;margin-top:50px;">اضافه کردن نویسنده جدید</h4><br />
        <p style="color:black;font-size:15px;font-weight:bold;color:orange;">لطفا فیلدهای مربوطه را با اطلاعات مناسب پر کنید.</p>

        <!--Name-->
        <div class="form-group">
            <label class="lbl">نام کامل نویسنده</label>
            <input type="text" style="max-width:100% !important;margin:0 auto;margin-top:10px;" id="Name" class="form-control" name="Name" placeholder="نام " required />
        </div><hr />

        <!--Nationality-->
        <div class="form-group">
            <label class="lbl">ملیت </label>
            <input type="text" style="max-width:100% !important;margin:0 auto;margin-top:10px;" id="Nationality" class="form-control" name="Nationality" placeholder="ملیت" required />
        </div><hr />

        <!--Writer-->
        <div class="form-group">
            <label class="lbl">سال تولد</label>
            <input type="text" style="max-width:100% !important;margin:0 auto;margin-top:10px;" id="BirthDay" class="form-control" name="BirthDay" placeholder="سال تولد" required />
        </div><hr />

        <!--DeathTime-->
        <div class="form-group">
            <label class="lbl">سال وفات</label>
            <input type="text" style="max-width:100% !important;margin:0 auto;margin-top:10px;" id="DeathTime" class="form-control" name="DeathTime" placeholder="سال وفات" required />
        </div><hr />



        <!--Image-->
        <div class="form-group">
            <label class="lbl">تصویر شاخص</label>
            <input type="file" name="Fileup" id="Fileup" required />
        </div><hr />


        <!--Content-->
        <div class="form-group">
            <label class="lbl">متن</label><br />
            <textarea id="mytextarea" name="mytextarea"></textarea>
        </div><hr /><br />


        <div class="form-group">
            <button class="btn btn-danger">تایید</button>

        </div>
    </div>
    }


</div>


@section scripts
{
    <script src="~/Content/js/jquery-1.10.2.min.js"></script>
    <script src="~/Content/ckeditor/ckeditor.js"></script>
    <script src="~/Content/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#mytextarea').ckeditor();
        });
    </script>
}

Book Store/Areas/Writer/Views/Writer/EditWriter.cshtml
@model Book_Store.Models.TBL_Writer
@{
    ViewBag.Title = "EditWriter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ChangeWriterStatus</h2>

<div class="container" style="margin-top:10px;">

    @using (Html.BeginForm("EditWriter", "Writer", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <div class="Frm" id="AddProductForm">
        <h4 style="font-weight:bold;text-align:center;margin-top:50px;">ویرایش نویسنده</h4><br />
        <p style="color:black;font-size:15px;font-weight:bold;color:orange;">لطفا فیلدهای مربوطه را با اطلاعات مناسب پر کنید.</p>

        <!--ID-->
        <input type="text" style="display:none" value="@Model.ID" name="TID" />
        <!--Name-->
        <div class="form-group">
            <label class="lbl">نام کامل نویسنده</label>
            <input type="text" style="max-width:100% !important;margin:0 auto;margin-top:10px;" id="Name" class="form-control" name="Name" value="@Model.FullName" required />
        </div><hr />

        <!--Nationality-->
        <div class="form-group">
            <label class="lbl">ملیت </label>
            <input type="text" style="max-width:100% !important;margin:0 auto;margin-top:10px;" id="Nationality" class="form-control" name="Nationality" value="@Model.Nationality" required />
        </div><hr />

        <!--Writer-->
        <div class="form-group">
            <label class="lbl">سال تولد</label>
            <input type="text" style="max-width:100% !important;margin:0 auto;margin-top:10px;" id="BirthDay" class="form-control" name="BirthDay" value="@Model.Birthday" required />
        </div><hr />

        <!--DeathTime-->
        <div class="form-group">
            <label class="lbl">سال وفات</label>
            <input type="text" style="max-width:100% !important;margin:0 auto;margin-top:10px;" id="DeathTime" class="form-control" name="DeathTime" value="@Model.Birthday" required />
        </div><hr />



        <!--Image-->
        <div class="form-group">
            <label class="lbl">تصویر شاخص</label>
            <input type="file" name="Fileup" id="Fileup" />
        </div><hr />


        <!--Content-->
        <div class="form-group">
            <label class="lbl">متن</label><br />
            <textarea id="mytextarea" name="mytextarea">@Model.Writer_Content</textarea>
        </div><hr /><br />


        <div class="form-group">
            <button class="btn btn-danger">تایید</button>

        </div>
    </div>
    }


</div>


@section scripts
{
    <script src="~/Content/js/jquery-1.10.2.min.js"></script>
    <script src="~/Content/ckeditor/ckeditor.js"></script>
    <script src="~/Content/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#mytextarea').ckeditor();
        });
    </script>
}

Book Store/Areas/Writer/Views/Writer/ShowAllWriters.cshtml
@model PagedList.IPagedList<Book_Store.Models.TBL_Writer>
@{
    ViewBag.Title = "AllWriters";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using PagedList.Mvc


<div class="container" style="margin-top:50px;">
    <h3 style="text-align:center;font-weight:bold;margin-bottom:50px;">مدیریت نویسنده ها </h3>


    <table class="table table-striped" style="margin-top:80px;margin-bottom:100px;">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">نام و نام خانوادگی</th>
                <th scope="col"> وضعیت نمایش</th>
                <th scope="col">  تغییر وضعیت نمایش</th>
                <th scope="col">ویرایش</th>

                <th scope="col">حذف</th>
                <th scope="col">جزئیات</th>
            </tr>
        </thead>
        @foreach (var test in Model)
        {
            <tbody>
                <tr>
                    <td style="font-weight:bold;">@test.ID</td>
                    <td style="font-weight:bold;">@test.FullName</td>

                    @if (@test.Status == 0)
                    {
                        string Stat = "در حال بررسی";
                        <td style="font-weight:bold;">@Stat</td>
                    }
                    else if (@test.Status == 1)
                    {
                        string Stat = "ثبت شده";
                        <td style="font-weight:bold;">@Stat</td>
                    }
                    <td>@Html.ActionLink("تغییر", "ChangeWriterStatus", "Writer", new { id = @test.ID }, new { @class = "btn alert-info" })</td>
                    <td>@Html.ActionLink("ویرایش", "EditWriter", "Writer", new { id = @test.ID }, new { @class = "btn alert-success" })</td>

                    <td>@Html.ActionLink("حذف", "DeleteUser", "Admin", new { id = @test.ID }, new { @class = "btn alert-danger" })</td>
                    <td>@Html.ActionLink("مشاهده کامل", "ShowWriterDetail", "Writer", new { id = @test.ID }, new { @class = "btn alert-info" })</td>

                </tr>

            </tbody>
        }
    </table><br />
    @Html.PagedListPager(Model, page => Url.Action("ShowAllWriters", new { page, pageSize = Model.PageSize }))



</div>

Book Store/Areas/Writer/Views/Writer/ShowWriterDetail.cshtml
@model Book_Store.Models.TBL_Writer
@{
    ViewBag.Title = "ShowWriterDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="margin-top:50px;">

    <div class="row">

        <div class="col-lg-4 col-md-3 col-sm-10" style="margin-bottom:20px;">
            <img class="Writer-img" src="~/Content/img/Writers/@Model.Image" />
            <ul id="ul-writer">
                <li>نام : @Model.FullName</li>
                <li>  سال تولد : @Model.Birthday میلادی</li>
                <li>وفات : @Model.Deathdate میلادی</li>
                @foreach(var items in Model.TBL_Product)
                {
                    <li>@items.Name</li>
                }
            </ul>
        </div>
        <div class="col-lg-8 col-md-9 col-sm-12">
            <table class="table table-striped" id="tbl-writer-data" style="margin-top:80px;margin-bottom:100px;">
                <tbody class="vtc">
                    <tr>
                        <td style="font-weight:bold;">نام : @Model.FullName</td>
                        <td style="font-weight:bold;">  سال تولد : @Model.Birthday میلادی</td>
                        <td style="font-weight:bold;"> وفات : @Model.Deathdate میلادی</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="container" style="text-align:justify;margin-bottom:50px;font-size:15px;">
        @Html.Raw(Model.Writer_Content)
    </div>
   

</div>